# Generated by Django 3.1.7 on 2021-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_server_loogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_loogin',
            name='password1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server_loogin',
            name='password2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
