# Generated by Django 3.1.7 on 2021-04-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210225_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_name',
            fields=[
                ('CountryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=50)),
                ('TwoCharCountryCode', models.CharField(max_length=2)),
                ('ThreeCharCountryCode', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='city_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=50)),
                ('countryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.country_name')),
            ],
        ),
    ]
