# Generated by Django 3.1.7 on 2021-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210422_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_products',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
