# Generated by Django 3.1.7 on 2021-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210424_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverice_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=20)),
            ],
        ),
    ]
