# Generated by Django 3.1.7 on 2021-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_serverice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('product_names', models.CharField(max_length=20)),
                ('product_descriptions', models.CharField(max_length=20)),
                ('product_service', models.CharField(max_length=20)),
                ('approved', models.CharField(max_length=20)),
            ],
        ),
    ]
