# Generated by Django 3.1.7 on 2021-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_approveds_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_name',
            name='CountryID',
        ),
        migrations.RemoveField(
            model_name='country_name',
            name='ThreeCharCountryCode',
        ),
        migrations.RemoveField(
            model_name='country_name',
            name='TwoCharCountryCode',
        ),
        migrations.AddField(
            model_name='country_name',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
