# Generated by Django 3.1.7 on 2021-06-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20210616_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_name',
            name='id',
        ),
        migrations.AddField(
            model_name='country_name',
            name='CountryID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
